### PR TITLE
Initial base4kids schema

### PR DESCRIPTION
**Pull request by paraenggu**
This PR adds the initial definition of the Base4Kids LDAP schema.

### CODE REVIEW

**Review by zwif — CHANGES_REQUESTED** [review]
We do have groups with two related Nextcloud Folder/Shares (due to permissions). In order to be able to represent both:

The ObjectClass `base4kidsGroup` needs an additional attribute for the `ShareId` of the second Nextcloud Folder/Share.

**Comment by paraenggu** [comment]
@zwif: Would you like to have the current `base4kidsNextCloudShareId` attribute multivalued, or do you prefer two independent attributes? In the later case, could you please propose two names, which would reflect your use case? Thanks

**Comment by zwif** [comment]
@paraenggu: Two independent attributes are prefered. Names could be something like:

- `base4kidsNextcloudShareId` representing the "normal" Folder
- `base4kidsNextcloudTemplatesShareId` representing the "`-Vorlage`" Folder

**Comment by paraenggu** [comment]
@zwif I've added two additional attributes:
* `base4kidsNextCloudClassShareId` (normal class folder)
* `base4kidsNextCloudClassTemplateShareId` (template class folder)
Is this OK for you?

**Review by zwif — APPROVED** [review]

**Comment by beatrubi** [comment]
From my point of view the schema looks OK, I found the desired functionality. Indices are looking correct, we might consider `SINGLE-VALUE` on attributes where we expect only a single value. Probably all attributes with the exception of `base4kidsRole`.

**Pull request merged**
